name: Publish to Cocoapods

on:
  push:
    tags:
    - '*'

jobs:
  publish-to-cocoapods:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: gem install cocoapods
      - name: Validate podspec
        run: pod spec lint --allow-warnings
      - name: Publish podspec
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
